### ISSUE TITLE
Unexpected token import error

### ISSUE THREAD

**Issue by martinschayna** [tornqvist/run-em#1]
I would to use run-em in most simplest way, for running scripts in subproject. This is my structure:

```
proj/
  package.json
  index.js
  subproj/
    package.json
    index.js
```

Content of `proj/package.json`:

``` json
{
  "name": "proj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "run-em subproj test"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "run-em": "^0.2.1"
  }
}
```

Content of `proj/subproj/package.json`:

``` json
{
  "name": "subproj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

I have successfully installed both projects and tried to run test in parent project:

```
$ npm test

> proj@1.0.0 test /home/user/Workspace/proj
> run-em subproj test

/home/user/Workspace/proj/node_modules/run-em/index.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:405:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/user/Workspace/proj/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/Workspace/proj/node_modules/run-em/bin/run-em:6:13)
    at Module._compile (module.js:398:26)
npm ERR! Test failed.  See above for more details.
```

This is my environment:

```
$ node -v
v5.4.0
$ npm -v
3.3.12
```

I have also tried to use run-em globally but with the same error. It looks like something doesn't transpile ES6 code. I have also tried to put `.babelrc` file to both project, but without success. What am I doing wrong?

**Comment by tornqvist** [comment]
I am sorry but this project is not production ready yet. I have yet to implement some kind of build step. If you however would like to use it in the meantime, try using [babel-cli](https://babeljs.io/docs/usage/cli/) to run the uncompiled ES2015 module.

`$ npm install --save-dev babel-cli`

And change your test script in `proj/package.json` to `babel-node npm_modules/.bin/run-em subproj test`
